# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   
  
  # Box base
  # https://www.vagrantup.com/docs/boxes
  config.vm.box = 'bento/ubuntu-20.04'

  # Hostname
  config.vm.hostname = 'ippd-2020'
  
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  #config.vm.box_check_update = true
  config.vm.boot_timeout = 240

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Diretório compartilhado
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Cria diretório compartilhado no diretório home do usuário vagrant
  config.vm.synced_folder "./vm-home", "/home/vagrant/shared", create:true



  #
  # Configurações do hipervisor para cada máquina virtual
  #
  config.vm.provider :virtualbox do |vbox|
    
    # Nome da VM no Virtualbox
    vbox.name = 'ippd-2020'

    # Memory - default 1GB
    vbox.memory = 1000
    
    # CPU Number - default: 1
    vbox.cpus = 1
    
    # Ativa a GUI do Virtualbox
    vbox.gui = true

  end



  # 
  # Configurações avançadas
  # 

  # Provisionamento
  config.vm.provision "shell", path: "./provision.sh"

  # Configuração para cacheamento dos pacotes
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
        
    # OPTIONAL: If you are using VirtualBox, you might want to use that to enable
    # NFS for shared folders. This is also very useful for vagrant-libvirt if you
    # want bi-directional sync
    config.cache.synced_folder_opts = {
      type: :nfs,
            # The nolock option can be useful for an NFSv3 client that wants to avoid the
            # NLM sideband protocol. Without this option, apt-get might hang if it tries
            # to lock files needed for /var/cache/* operations. All of this can be avoided
            # by using NFSv4 everywhere. Please note that the tcp option is not the default.
            mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
     }
        # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  end
    
end